---
Name: dataobjectsorterroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'dataobjectsorter//$Action/$ID/$OtherID/$ThirdID/$FourthID/$FifthID/' : 'DataObjectSorterController'
    'dataobjectonefieldupdate//$Action/$ID/$OtherID/$ThirdID/' : 'DataObjectOneFieldUpdateController'
    'dataobjectonefieldonerecordupdate//$Action/$ID/$OtherID/$ThirdID/' : 'DataObjectOneFieldOneRecordUpdateController'
    'dataobjectonerecordupdate//$Action/$ID/$OtherID/$ThirdID/' : 'DataObjectOneRecordUpdateController'
